# You can specify here the packages and classes
# that contain your business operations
---
packages-to-scan:
  - com.test.pack.operation.*
  - org.test.operation.*
classes:
  - some.pack.operation.impl.DummyOperation